dependencies:
  - rich
  - filelock >= 3.4.0

dev-dependencies:
  - pyyaml

optional-dependencies:
  # 下载时使用requests包，并且支持socks5代理
  # Use requests package for downloading, and support socks5 proxy
  requests:
    - 'requests[socks]'

  # 集成frida hook框架，支持android、ios hook
  # Integrate frida hook framework, support android, ios hook
  frida:
    - frida>=15.0.0

  # 集成objection框架，支持android、ios hook
  # Integrate objection framework, support android, ios hook
  objection:
    - objection

  # 为grep提供服务，可解析apk、elf等文件格式
  # Provide services for grep, can parse apk, elf and other file formats
  # (Note: For mac system, you need to install: brew install libmagic)
  lief:
    - lief>0.10.1
    - python-magic; platform_system=="Linux"
    - python-magic; platform_system=="Darwin"
    - python-magic-bin; platform_system=="Windows"

  # 使用ssh连接越狱后的iphone
  # Use ssh to connect to jailbroken iphone
  ssh:
    - paramiko
    - scp

  # 用于解析证书时使用
  # Used for parsing certificates
  ssl:
    - pyOpenSSL

  # 用于docker/podman容器管理
  # Used for docker/podman container management
  container:
    - GitPython
    - jinja2
    - pyyaml
