dependencies:
  - rich
  - filelock >= 3.4.0

dev-dependencies:
  - pyyaml

optional-dependencies:
  requests:
    - 'requests[socks]'
  frida:
    - frida>=15.0.0
  objection:
    - objection
  lief:
    - lief>0.10.1
    - python-magic; platform_system=="Linux"
    - python-magic; platform_system=="Darwin"
    - python-magic-bin; platform_system=="Windows"
  ssh:
    - paramiko
    - scp
  ssl:
    - pyOpenSSL
  container:
    - GitPython
    - jinja2
    - pyyaml
