services:
  portainer:
    image: portainer/portainer-ce:{{ PORTAINER_TAG }}
#   {% if int(PORTAINER_EXPOSE_PORT, 0) > 0 %}
    ports:
      - '{{ PORTAINER_EXPOSE_PORT }}:9000'
#   {% endif %}
    volumes:
      - '{{ manager.container_host }}:/var/run/docker.sock'
      - '{{ container.get_app_path("data") }}:/data'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
