services:
  nginx:
    volumes:
      - '{{ mkdir(APP_PATH/"conf.d") | chown }}:/etc/nginx/conf.d'
    ports:
      - '{{ HTTP_PORT }}:{{ HTTP_PORT }}'
#     {% if HTTPS_ENABLE %}
      - '{{ HTTPS_PORT }}:{{ HTTPS_PORT }}'
#     {% endif %}
    networks:
      - nginx

networks:
  nginx:
    name: nginx
