services:
  nginx:
    container_name: nginx
    build:
      context: "{{ container.get_path() }}"
      dockerfile: "{{ container.get_docker_file_path() }}"
    restart: unless-stopped
    volumes:
      - "{{ container.get_app_path() }}/conf.d:/etc/nginx/conf.d"
    ports:
      - "{{ HTTP_PORT }}:{{ HTTP_PORT }}"
      - "{{ HTTPS_PORT }}:{{ HTTPS_PORT }}"
    networks:
      - nginx
    logging:
      options:
        max-size: 1m

networks:
  nginx:
    name: nginx
